services:
  backend:
    build:
      context: ../backend
    container_name: stock-scanner-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      UPSTOX_ACCESS_TOKEN: "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI2VEJWRjUiLCJqdGkiOiI2YTI5NmFkZDlkMDZiZjM5MWFlMjQ2MzUiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc4MTA5OTIyOSwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzgxMTI4ODAwfQ.IxE1vtwnAzU75ttFJ43ASmKt4FTk7Vhb_Ivn0-bKpNY"

  postgres:
    image: postgres:16
    container_name: stock-scanner-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stockscanner
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: K16101996k
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

